# Ignore TypeScript rules S2201 and S2202 globally
sonar.issue.ignore.multicriteria=e1,e2

# Disable typescript:S2201
sonar.issue.ignore.multicriteria.e1.ruleKey=typescript:S2201
sonar.issue.ignore.multicriteria.e1.resourceKey=**

sonar.issue.ignore.multicriteria.e2.ruleKey=typescript:S125
sonar.issue.ignore.multicriteria.e2.resourceKey=**

