name: utils -- build

env:
  PACKAGE_DIR: packages/utils
  TASKFOLDERS_ROOT: ${{ github.workspace }}

on:
  workflow_dispatch:

  push:
    branches: 
      - main
      - develop
    paths:
      - "${{ env.PACKAGE_DIR }}/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.PACKAGE_DIR }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Global dependencies
        run: cd ../.. && npm install

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

