name: Build

on:
  push:
    branches: [ main ]
    paths:
      - "packages/utils/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/utils 
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      # - name: Build (optional)
      # run: npm run build  # Replace with your build command if applicable


