name: Utils

on:
  push:
    branches: [ main ]
    paths:
      - "packages/utils/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/utils 
      env:
        TASKFOLDERS_ROOT: ${{ env.GITHUB_REPOSITORY }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Global dependencies
        run: cd ../.. && npm install

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test:ci

      # - name: Build (optional)
      # run: npm run build  # Replace with your build command if applicable


